---
name: "mongo-devices-2-snow"
description: "Get mongo devices and send to servicenow."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "arubaimc.mongo-devices-2-snow"
