---
name: "imc-realtime-2-mongo"
description: "Get all Aruba IMC realtime alarms and send to mongo."
enabled: true

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "arubaimc.imc-realtime-2-mongo"
