---
name: "imc-devices-2-snow"
description: "Get all Aruba IMC devices and send to mongo then servicenow."
enabled: false

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "arubaimc.imc-devices-2-snow"
