---
name: "mongo-alarms-2-snow"
description: "Get mongo alarms and send to servicenow."
enabled: true

trigger:
  type: "core.st2.IntervalTimer"
  parameters:
    delta: 5
    unit: minutes

action:
  ref: "arubaimc.mongo-alarms-2-snow"
